// AUTO-GENERATED by scripts/fetch_guide_photos.py, Unsplash hotlinks.
// Per Unsplash API guidelines: hotlink the CDN url (do NOT self-host) +
// attribute the photographer & Unsplash. Re-run the script to refresh.
export type GuidePhoto = { url: string; alt: string; photographer: string; photographerUrl: string }
export const GUIDE_PHOTOS: Record<string, GuidePhoto> = {
  "cubs-game-day-chicago": {
    "url": "https://images.unsplash.com/photo-1519407451944-22e820099775?ixid=M3w5NjI3MjR8MHwxfHNlYXJjaHwxfHxXcmlnbGV5JTIwRmllbGQlMjBDaGljYWdvfGVufDF8MHx8fDE3Nzk5MTUxNjl8MA&ixlib=rb-4.1.0&w=1600&q=80&fit=crop&crop=entropy",
    "alt": "Wringley Field Home of Chicago Cubs",
    "photographer": "Heather Maguire",
    "photographerUrl": "https://unsplash.com/@hmaguire?utm_source=312deals&utm_medium=referral"
  },
  "college-bars-chicago": {
    "url": "https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?ixid=M3w5NjI3MjR8MHwxfHNlYXJjaHwxfHxjb2xsZWdlJTIwYmFyJTIwcHViJTIwZnJpZW5kcyUyMGRyaW5rc3xlbnwxfDB8fHwxNzc5OTE1MTcwfDA&ixlib=rb-4.1.0&w=1600&q=80&fit=crop&crop=entropy",
    "alt": "people holding drinks during day",
    "photographer": "Fred Moon",
    "photographerUrl": "https://unsplash.com/@fwed?utm_source=312deals&utm_medium=referral"
  },
  "dog-friendly-patios-chicago": {
    "url": "https://images.unsplash.com/photo-1776812007560-564da574ba72?ixid=M3w5NjI3MjR8MHwxfHNlYXJjaHwxfHxkb2clMjByZXN0YXVyYW50JTIwcGF0aW8lMjBvdXRkb29yfGVufDF8MHx8fDE3Nzk5MTUxNzB8MA&ixlib=rb-4.1.0&w=1600&q=80&fit=crop&crop=entropy",
    "alt": "People sit at tables outside a brick building.",
    "photographer": "Freddie Addery",
    "photographerUrl": "https://unsplash.com/@freddieaddery?utm_source=312deals&utm_medium=referral"
  },
  "fathers-day-chicago-2026": {
    "url": "https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?ixid=M3w5NjI3MjR8MHwxfHNlYXJjaHwxfHxzdGVhayUyMGRpbm5lciUyMHN0ZWFraG91c2V8ZW58MXwwfHx8MTc3OTkxNTE3MXww&ixlib=rb-4.1.0&w=1600&q=80&fit=crop&crop=entropy",
    "alt": "fried food on black pan",
    "photographer": "Madie Hamilton",
    "photographerUrl": "https://unsplash.com/@mham3816?utm_source=312deals&utm_medium=referral"
  }
}
